name: SonarQube Analysis

on:
  push:
    branches:
      - main      # or any branch you want to trigger the workflow
  pull_request:
    branches:
      - main      # or any branch you want to trigger the workflow on PR

jobs:
  sonar:
    name: Run SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK (if using Java)
      uses: actions/setup-java@v2
      with:
        java-version: '11'    # Modify to match your Java version if applicable
        distribution: 'adoptopenjdk'

    - name: Cache SonarQube dependencies
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.java') }}  # Adjust to your language or dependencies

    - name: Set up SonarQube Scanner
      uses: sonarsource/sonarcloud-github-action@v1
      with:
        sonar-token: efb75e602c7c4bec514d24a0c5fc9f915040ced3

    - name: Run SonarQube Analysis
      run: |
        sonar-scanner -Dsonar.projectKey=SONAR_TOKEN
                      -Dsonar.organization=${{ secrets.SONAR_ORG }}
                      -Dsonar.host.url=https://sonarcloud.io  # Modify for SonarQube server if self-hosted
